name: Code Review
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ${{ github.repository }}@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} 