name: Code Review Bot

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
      checks: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Load repository configuration
        run: |
          python .github/scripts/load-config-script.py
        id: config

      - name: Parse review preference
        run: |
          python .github/scripts/parse_review_preference.py
        id: review_pref

      - name: Run code analysis
        run: |
          python .github/scripts/run_analysis.py
        id: analysis

      - name: Generate review
        run: |
          python .github/scripts/generate_review.py
        id: review

      - name: Post review comments
        if: steps.review_pref.outputs.review_type == 'bot+human'
        run: |
          python .github/scripts/post_comments.py

      - name: Auto-approve PR
        if: steps.review_pref.outputs.review_type == 'bot-only' && steps.analysis.outputs.all_checks_passed == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              event: 'APPROVE',
              body: 'All automated checks passed. PR approved by GitHub Review Bot.'
            })